# Generated by Django 3.2.17 on 2023-02-09 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('price', models.FloatField(verbose_name='Preço')),
                ('score', models.FloatField(verbose_name='Popularidade')),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
