# Generated by Django 3.2.17 on 2023-02-11 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='score',
            field=models.PositiveIntegerField(verbose_name='Popularidade'),
        ),
    ]
